name: qsblue-niri-dms
image-version: 43
base-image: ghcr.io/wayblueorg/hyprland
modules:
  - type: dnf
    repos:
      copr:
        - avengemedia/dms
        - avengemedia/danklinux
        - ublue-os/packages
  - type: rpm-ostree        
    install:
      - niri
      - alacritty
      - xwayland-satellite
      - greetd
      - greetd-tuigreet
      - greetd-selinux
      - qt6-qtwayland
      - xdg-desktop-portal-gnome
      - wl-clipboard
      - network-manager-applet
      - quickshell
      - matugen
      - material-symbols-fonts
      - dms
      - dms-greeter
      - wlsunset
      - cliphist
      - imv
      - mpv
      - nemo
      - mousepad
      - hyprpolkitagent
    remove:
      - firefox
      - firefox-langpacks
      - sddm
replace:  # Force newer Qt (6.10.1 from F43 updates)
      - packages:
          - qt6-qtbase
          - qt6-qtdeclarative
          - qt6-qtwayland  # Core Qt deps for Quickshell/DMS
        from-url:  # Pull from Fedora 43 updates mirror
          - https://archives.fedoraproject.org/pub/archive/fedora/linux/updates/43/Everything/x86_64/Packages/q/qt6-qtbase-6.10.1-1.fc43.x86_64.rpm
          - https://archives.fedoraproject.org/pub/archive/fedora/linux/updates/43/Everything/x86_64/Packages/q/qt6-qtdeclarative-6.10.1-1.fc43.x86_64.rpm
          - https://archives.fedoraproject.org/pub/archive/fedora/linux/updates/43/Everything/x86_64/Packages/q/qt6-qtwayland-6.10.1-1.fc43.x86_64.rpm
      # Add more Qt subpkgs if needed (e.g., qt6-qtquick3d for full Quickshell)
  - type: files
    files:
      - source: system_files
        destination: /

  - type: systemd
    system:
      enabled:
        - greetd
        - firewalld
        - cliphist

description: "QuickBlue - Niri + DankMaterialShell + DMS Greeter + Brave dev setup"
